export enum ENUM_NOTIFICATION_TYPE {
  REQUEST_RESPONSE = "REQUEST_RESPONSE",
  NEW_COMMENT = "NEW_COMMENT",
  COMMENT_REPLY = "COMMENT_REPLY",
  POST_APPROVED = "POST_APPROVED",
  POST_APPROVAL_REMINDER = "POST_APPROVAL_REMINDER",
}

export enum ENUM_NOTIFICATION_STATUS {
  UNREAD = "UNREAD",
  READ = "READ",
}
